"""add resources

Revision ID: 516ffc3a6017
Revises: 3a5cabf9e9b8
Create Date: 2026-09-05 22:23:40.977442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516ffc3a6017'
down_revision: Union[str, Sequence[str], None] = '3a5cabf9e9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Enum('official_docs', 'article', 'video', 'paper', 'repo', 'interactive', name='resource_type'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_resources_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
    # Postgres native ENUM types are independent database objects, not
    # tied to the table that used them — dropping 'resources' above does
    # NOT drop this type. Same fix as c1482ba5cd70's message_role, applied
    # here up front rather than waiting to hit the "type already exists"
    # failure on a future re-run.
    sa.Enum(name='resource_type').drop(op.get_bind(), checkfirst=True)
